name: Laravel CI Pipeline

# Run the workflow on push and pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
          MYSQL_USER: root
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        # Wait for MySQL service to be ready
        timeout: 600s

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Use the PHP version your Laravel project requires
          extensions: mbstring, bcmath, pdo, pdo_mysql
          coverage: none

      # Step 3: Install Composer dependencies
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Step 4: Copy .env.example to .env
      - name: Copy .env
        run: cp .env.example .env

      # Step 5: Generate application key
      - name: Generate application key
        run: php artisan key:generate

      # Step 6: Set up the database (migrate)
      - name: Run migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: password
        run: php artisan migrate --force

      # Step 7: Run tests
      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: password
        run: php artisan test
